config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'


  resources :articles do
    get :search
  end
  resources :categories do
    get :search
  end



end

app/models/category.rb
class Category < ActiveRecord::Base


  has_many :articles
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController


	def index
	    @categories = Category.all.order("weight asc")
	end

	def show 
	end

	def new
		@category = Category.new
		respond_to do |format|
			format.js
		end
	end

	def create
		@category = Category.new(params_category)
		@category.save
		redirect_to admin_categories_path
	end


	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update(params_category)
		redirect_to :back
	end

	def destroy
		category = Category.find(params[:id])
		category.destroy
		redirect_to :back
	end

	def update_status
		category = Category.find(params[:id])
		status = category.status == "on" ? 'off' : 'on'
		category.update(:status=>status)
		if category.status == 'on'
		  render :json=> {'message': '上架'}
		else
		  render :json=> {'message': '下架'}
		end
	end

	private
	def params_category
		params.require(:category).permit!
	end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController



  def index
    pin = []
    pin << params[:one] if params[:one].present?
    pin << params[:two] if params[:two].present?
    pin << params[:three] if params[:three].present?
    pin << params[:four] if params[:four].present?
    pin << params[:five] if params[:five].present?
    pin << params[:six] if params[:six].present?
    red = [
      '01','02','03','04','05','06','07','08','09','10','11',
      '12','13','14','15','16','17','18','19',
      '20','21','22','23','24','25','26','27',
      '28','29','30','31','32','33'
    ]
    red = red - pin
    red_size = pin.count > 0 ? (6 - pin.count) : 6
    @counts = []
    number = params[:number] ||= 10
    blue = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16']

    number.to_i.times do |x|

      @counts << (pin + red.shuffle[0, red_size]).sort.join(" ") + " + " + blue.shuffle[0,1].join(",")
    end
    if params[:ref].present?
      ref = params[:ref].to_i
      array = []
      @counts.each do |count|
        array << count if count.split("+").last.to_i == ref
      end
      @counts = array
    end
    return @counts
  end


end

app/views/categories/index.html.erb
<h1 style="font-size: 70px;">双色球机选器
(<a href="/articles" class='btn btn-sm btn-danger'>大乐透机选器</a>)
</h1>
<br>
<%=form_tag categories_path,method: :get do%>
  红1: <input style="height: 60px;width: 60px;" name="one" value="<%=params[:one]%>">
  红2: <input style="height: 60px;width: 60px;" name="two" value="<%=params[:two]%>">
  红3: <input style="height: 60px;width: 60px;" name="three" value="<%=params[:three]%>">
  红4: <input style="height: 60px;width: 60px;" name="four" value="<%=params[:four]%>">
  红5: <input style="height: 60px;width: 60px;" name="five" value="<%=params[:five]%>">
  红6: <input style="height: 60px;width: 60px;" name="six" value="<%=params[:six]%>">
  蓝球: <input name="ref" style="height: 60px;width: 100px;" type="number" oninput="if(value>16)value=16" value="<%=params[:ref]%>">
  注数: <input name="number" value='10' style="height: 60px;width: 100px;" type="number" oninput="if(value>10000)value=10000" placeholder="请输入机选注数">
  <%=submit_tag '机选', class: 'btn btn-sm btn-info'%>(共：<%= @counts.count%>注)
<%end%>
<br>
<table class="table">
  <tbody>
  <tr>
    <td colspan=3>机选结果</td>
  </tr>
  <% @counts.each_slice(2) do |counts|%>
    <tr>
      <% counts.each do |count|%>
        <td><%=count%></td>
      <%end%>
    </tr>
  <%end%>
  </tbody>
</table>